server.port=8000
//net start mongoDB
spring.data.mongodb.uri=mongodb+srv://<email>:<password>.mongodb.net/
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<email>
spring.mail.password=<app_password>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true